### ISSUE TITLE
Documentation example for getting the address or a register

### ISSUE THREAD

**Issue by jeras** [krcb197/PeakRDL-python#111]
The most basic use case for a generator in my experience was to get the address of a register to use in a testbench or application. Could you provide such an example in the documentation?

**Comment by krcb197** [comment]
Part of the reason for a Register Abstraction Layer (RAL) generated by peakrdl-python, is to avoid the need to access the addresses of registers. So it was a conscious decision not to include an example accessing the address of a register. However, the generated RAL does include the addresses of all the registers and blocks, see the `address` property

**Comment by krcb197** [comment]
No further follow-up questions have be made to my original response so I am closing this.
