### ISSUE TITLE
Feature ideas, support for MicroPython/CircuitPython, `mmap`ping `/dev/uio*`

### ISSUE THREAD

**Issue by jeras** [krcb197/PeakRDL-python#112]
It would probably make sense to have a separate project for such an exporter, for now I just wrote it down so I don't just forget about it. CircuitPython has some concept of a register map, with some focus on a memory efficient implementation.
https://docs.circuitpython.org/projects/register/en/latest/

In the [PYNQ project](https://github.com/xilinx/pynq), it is possible to map a section of the address space through `/dev/mem` or better `/dev/uio*` (UIO device driver) using [mmap](https://docs.python.org/3/library/mmap.html) and [UIO](https://github.com/mvduin/py-uio). There is some relevant code in the RedPitaya repository also. I remember using [ctype](https://docs.python.org/3/library/ctypes.html) to define structures, which I used as pointers to a memory mapped peripheral in a Zynq SoC.

Both of this ideas focus on some kind of optimized implementation.
I did not look into PeakRDL-python internals yet, to be able to make specific suggestions, but I think the above project might offer some ideas which could be used to improve PeakRDL-python.

**Comment by jeras** [comment]
I looked further into MycroPython and found two ways to access memory mapped registers:

- `machine` [memory access](https://docs.micropython.org/en/latest/library/machine.html#memory-access),
- `uctypes` [access binary data in a structured way](https://docs.micropython.org/en/latest/library/uctypes.html).

Functions `machine.mem8/16/32` can be used as callbacks, while `uctypes` might provide better performance. For now I just searched for the available functionality, and I opened a [discussion](https://github.com/orgs/micropython/discussions/12861) to see if MicroPython developers can provide some feedback.

**Comment by jeras** [comment]
On a ZYNQ device (or some other SoC) the [`pydevmem` library](https://github.com/kylemanna/pydevmem/tree/master) (or something similar) can be used to create the read/write callbacks. See [this example](https://github.com/kylemanna/pydevmem/blob/master/examples/phymdio.py) on how to use devmem.

Various devmem implementations are already using a python `mmap` library.

UIO is an alternative to having unrestricted access to the entire memory through `/dev/mem/`.
Definitions in a DeviceTree specify the memory segment accessible through a `/dev/uio*/` device.

`udev` rules can be used to modify the enumeration of UIO devices, to use a name string from the DeviceTree instead of a simple number. It can also be used to give a non root user/group access to the device. Restricted address range and unprivileged user access makes UIO a more secure alternative to `/dev/mem/`. Another feature of UIO is mapping of interrupts into userspace.

The Python UIO library provides access to metadata from DeviceTree UIO entries, so the base address, window size, ...
It probably does not make sense to integrate is tightly with a Python code generator, but it is probably worth mentioning in the documentation.

**Comment by krcb197** [comment]
peakdl-python was really aimed at the high-level programmer who wanted to use the power of Python (iterators and enumerations etc...) for example, a large set of Device Validation Scripts that run on a PC connected to a target device with a JTAG probe. The code generated can get quite large, therefore, I am not sure it is suitable for small-footprint Python implementations (though I could be convinced otherwise), there is another project that might be am alternative starting point: peakrdl-python-simple.

That said the peakrdl-python RAL is designed to be route through to any call back scheme that a python function can define, so it should be possible to put  generated RAL onto of these methods for access to the hardware registers. There is an example in the documentation for building callbacks and integrating them.

**Comment by jeras** [comment]
I agree that a MicroPython exporter would be a separate project. I included it in this discussion, since it might be a source of ideas.

The idea to use the `ctypes` library still applies to this project.
I think it might provide better performance (less function call overhead) than the approach with callbacks.
In combination with mmap and UIO the generated Python code can be used to write drivers, and not just verification code.
I did not read obut this project internals enough yet to be able to tell is a `ctypes` generator would fit this project or it should be a separate one.

**Comment by krcb197** [comment]
I have thought about this a bit more, peakrdl-python is a framework for generating python code including a set of CI/CD. The actual code generated is dependent on the jinja2 template and base library. I can see some value in keep in the framework and simply adding an extra set of templates with optional base library to support an alternative output. 

I would happily collaborate this extra option within peakrdl-python alternatively you can fork and make a new generator reusing the infrastructure and CI. If you want to take the second route let me know and I will close this issue.

**Comment by kolpakchi** [comment]
To use full power of python we can just create a memory bridge between IC and PC and use it as any other memory. This [approach](https://github.com/enjoy-digital/litex/tree/master/litex/tools/remote) is used in litex project to link together FPGA based SoC and PC for debugging hardware. The bridge can be based on UART, ethernet or PCI-E, but the actual protocol is super simplistic.

**Comment by krcb197** [comment]
> To use full power of python we can just create a memory bridge between IC and PC and use it as any other memory. This [approach](https://github.com/enjoy-digital/litex/tree/master/litex/tools/remote) is used in litex project to link together FPGA based SoC and PC for debugging hardware. The bridge can be based on UART, ethernet or PCI-E, but the actual protocol is super simplistic.

I have taken a look at the litex project today, it would be very easy to adopt that to work with the peakrdl-python wrappers. Does anyone have a project that could be used to do some testing? I would love to be able to cross-reference an example and I am support someone who did that.

**Comment by krcb197** [comment]
Closing this issue as not clear change or improvement concluded from the thread and it has not be touched in over a year
