### ISSUE TITLE
Include Register/Field HWIF Signal Metadata

### ISSUE THREAD

**Issue by eehusky** [krcb197/PeakRDL-python#127]
Ive been using this library as part of a (i want to call it hodge podge but its required way less duct tape than i thought it would)  cocotb+cocotb-axiextension+peakrdl-regblock+verilator test bench conglomerate and got to thinking about a kinda handy add-on that i thought I would bring up (and secretly hoping someone might have already done this).

Would it be possible, as part of the generation of the python interface, to include some meta information about the field/register properties?

The kind of things id be looking to include (in something like an attribute dictionary for each field) would be stuff like the sw access properties and read/write access modifiers/counter properties.  You wouldn't do anything with them in this library other than include the information then it would be up to the user to use them for what ever nefarious testing purposes they can come up with.  Maybe just a serialized version of the parsed RDL for that field?

I haven't looked into the systemrdl parser enough to know if this exists but does each node get assigned a UUID or something that these different tools can use to cross reference each other?  So the regblock tool could export a report with a UUID - SignalName, the python tool would generate a UUID-Register report and then a third tool could use that to generate a closed loop register/hwif test bench using the generated software/hdl.

Not knowing any better....I think the way I'm going to go about it for my own purposes is parsing the rdl myself and walking that tree then looking up the matching register names here and the hwif ports exported by regblock (with --hwif-report).  But it seems like it would be less clunky/error prone to (since we are already generating tons of python code here and have access to all this info at the point of generation) include it here.

**Comment by krcb197** [comment]
@eehusky  

Generally, `peakrdl-python` ignores signals as it was intended to wrap the registers to provide a software interface. My initial reaction is that it should stay within this scope, as the danger is that this will bloat the generated code. Including the serialised systemRDL does not feel right as the user would then need to provide a systemRDL parser which would replicate a lot of what the compiler does already. 

Regarding a UUID, all the nodes have a `full_inst_name` property that provides a string which can be cross-referenced within the compiler using the `get_path()` method

However, some of the metadata is already present, for example, the generated API already takes into account the sw accessibility of the fields in the generated structure using one of these baseclasses: `FieldWriteOnly`, `FieldReadOnly` or `FieldReadWrite`. The register has similar behaviour. The fields class has a number of properties, to hold meta data for example the high and low bit positions within the register. Within reason, more could be added if there were some clear use cases, do you have some specific properties in mind?

**Comment by krcb197** [comment]
This issue has not been touched in a while, therefore it is being closed.
