### ISSUE TITLE
Error generating & reading from Mem with `memwidth` > 64 bits.

### ISSUE THREAD

**Issue by apstrike** [krcb197/PeakRDL-python#137]
Hello, it appears that due to the use of the `array.array` object when it comes to reading from a memory element (as well as when generating the testbench file), the tool does not support RDL maps with memories where the memory's `memwidth` is > 64 bits.

You can see this with the following example:

with the RDL file (test_mem_rdl.rdl)

``` 
addrmap test_mem_rdl {
    default regwidth = 32;
    default accesswidth = 32;

    external mem
    {
        name = "mem blk";
        mementries = 24;
        memwidth = 128;
        sw=rw;

    } my_m;

};


```

and the command: `peakrdl python -o ./ test_mem_rdl.rdl`

the following error:

``` 
[aporat@aporat-dev tmp]$ peakrdl python -o ./ --async test_mem_rdl.rdl
Traceback (most recent call last):
  File "/home/aporat/.pyenv/versions/3.12.3/bin/peakrdl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/aporat/.pyenv/PeakRDL-gts/src/peakrdl/main.py", line 165, in main
    options.subcommand.main(importers, options)
  File "/home/aporat/.pyenv/PeakRDL-gts/src/peakrdl/subcommand.py", line 154, in main
    self.do_export(top, options)
  File "/home/aporat/.pyenv/versions/3.12.3/lib/python3.12/site-packages/peakrdl_python/__peakrdl__.py", line 87, in do_export
    peakrdl_exporter.export(
  File "/home/aporat/.pyenv/versions/3.12.3/lib/python3.12/site-packages/peakrdl_python/exporter.py", line 394, in export
    stream.dump(fp)
  File "/home/aporat/.pyenv/versions/3.12.3/lib/python3.12/site-packages/jinja2/environment.py", line 1618, in dump
    fp.writelines(iterable)
  File "/home/aporat/.pyenv/versions/3.12.3/lib/python3.12/site-packages/jinja2/environment.py", line 1662, in __next__
    return self._next()  # type: ignore
           ^^^^^^^^^^^^
  File "/home/aporat/.pyenv/versions/3.12.3/lib/python3.12/site-packages/jinja2/environment.py", line 1354, in generate
    yield self.environment.handle_exception()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aporat/.pyenv/versions/3.12.3/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/aporat/.pyenv/versions/3.12.3/lib/python3.12/site-packages/peakrdl_python/templates/addrmap_tb.py.jinja", line 849, in top-level template code
    Array('{{get_array_typecode(node.get_property('memwidth'))}}', [value]))

  File "/home/aporat/.pyenv/versions/3.12.3/lib/python3.12/site-packages/peakrdl_python/lib/utility_functions.py", line 61, in get_array_typecode
    raise ValueError(f'unhandled width {width:d}')
ValueError: unhandled width 128

```

When I add the `--skip_test_case_generation` option, the tool generates the files ok. However due to the use of `array.array` for reads, I still reach the same `ValueError` statement.

I.e. when running a simulation with Cocotb and attempting to read the memory with `await test_rdl_mem.my_m.read(0, 1)` I get the following error:

``` 
#   4564.00ns INFO     cocotb.regression                  mem_rdl_test failed
#                                                         Traceback (most recent call last):
#                                                           File "/home/aporat/tmp/test_rdl_mem_cocotb.py", line 683, in mem_rdl_test
#                                                             d = await test_rdl_mem.my_m.read(i, 1)
#                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#                                                           File "/home/aporat/tmp/test_mem_rdl/lib/memory.py", line 617, in read
#                                                             data_read = Array(self.array_typecode, [0 for _ in range(number_entries)])
#                                                                               ^^^^^^^^^^^^^^^^^^^
#                                                           File "/home/aporat/tmp/test_mem_rdl/lib/memory.py", line 137, in array_typecode
#                                                             return get_array_typecode(self.width)
#                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#                                                           File "/home/STRIKETECH/aporat/tmp/test_mem_rdl/lib/utility_functions.py", line 61, in get_array_typecode
#                                                             raise ValueError(f'unhandled width {width:d}')
#                                                         ValueError: unhandled width 128
```

I'm assuming that the `array` class is being used for some type safety and to mimic how a C proram would interpret the data. I'm not sure of an alternative for this. 
Would it maybe be sensible for the case of the memory element width being > 64 bits to allow for the return type to be an array of unsigned char's? 
I'd think that this would best represent what one would expect from a C program that reads/writes an element like this.

Thanks,
Aylon

**Comment by krcb197** [comment]
Aylon (@apstrike) 

Thank you for taking the time to document this. I was aware of this issue the original decision was based on:
- Memory and speed (for example using a list would have been the obvious alternative)
- Trying to avoid library dependencies, I was trying to make sure this stayed "pure python" as much as possible
- Avoiding needing problems with endianness or byte ordering, as soon as the width of the returned data does not match the memory width potential confusion exists

However, it did come with the risk that someday the limitation of arrays would be hit. I had made the assumption that is was better to have efficiency. One reason arrays work in units of either 32-bit or 64-bit chunks is that C and most hardware memories get built this way if they are accessed in hardware.  I would be interested in the use case for a 128-bit wide memory bus in the hardware. 

However, this is all legal in systemRDL so in hindsight I am not sure this was the right choice. I have checked the specification, memories do not even need to be 2ⁿ wide, so a memory which was 9-bit width is legal, but likely to be unusual. I know 36-bit memories are used in hardware to add ECC but the exposed memory width is normally 32-bit.

The other main choice for efficient arrays in Python is Numpy, however, it does not have a 128-bit type either and this would break the "pure python" ideal.

One nice thing about python is the underlying integer class can support integers of any width. My favoured solution to this would be moving to a list of integers. Most people who are using the wrapper would need to make minor changes (including to the call-backs protocol) so rolling out this change would need care, I would recommend introduce the new version with a build option initially (Array mode or list mode). Does that seem reasonable to you?

**Comment by apstrike** [comment]
hi @krcb197, thanks for such a quick reply. 


> I have checked the specification, memories do not even need to be 2ⁿ wide, so a memory which was 9-bit width is legal, but likely to be unusual.

I didn't notice this myself either! I also had the assumption that memory widths have to have similar rules to that of register widths in relation to the access width.

> One nice thing about python is the underlying integer class can support integers of any width. My favoured solution to this would be moving to a list of integers


As for changing the underlying data type to a list of integers, I think that makes plenty of sense. I agree that it's not the most type safe which is annoying but I'm not sure of an alternative. Maybe a tuple instead of list would be safer for reads?

> One reason arrays work in units of either 32-bit or 64-bit chunks is that C and most hardware memories get built this way if they are accessed in hardware. I would be interested in the use case for a 128-bit wide memory bus in the hardware.

I think a reasonable use case for a memory that is (say) 128-bit wide is when the underlying element is a struct being communicated from SW to HW. There's not really a guarantee of automaticity here, but that may not matter for some users or they may build in their own valid or read-modify-write functionality. 

Lmk how I can help in this process!

Thanks,
Aylon

**Comment by krcb197** [comment]
@apstrike 

I am currently in the middle of another feature to add a lightweight simulator to the package. This will be next in the queue

**Comment by krcb197** [comment]
@apstrike 

There is a fix to this issue with two changes:
- New list-based block callbacks in addition to the existing array.array ones, the array.array ones are called legacy to allow people a couple of versions to sort things out
- New wrapper API with list returns for block accesses, this can be turned off using a command line switch or export option (`legacy_block_access`)

I could not see an easy way to do this without making a breaking change so I need to put a bit more thought into how to make this journey simpler for people. 

This is on a pre-release pypy release, which can be installed as follows:
``` bash
pip install peakrdl-python --pre
```

Can you test this and let me know how you get on/

**Comment by apstrike** [comment]
@krcb197, I tried out the pre-release and it seemed to work well! Thanks for working on the changes so quick.

One thing I did notice is that accessing a virtual register within a `Mem` block only gives access to the register of the first element of the memory.

So for example for,

```
external mem
    {
        name = "mem blk";
        mementries = 24;
        memwidth = 128;
        sw=rw;

       reg {
           regwidth=128;
           field {} my_field[32];
      } my_reg;
      

    } my_m;
```

I can do `my_m.my_reg.read()`, which will read the 0th my_reg. But I can't do something like `my_m[3].my_reg.read()` to read `my_reg` at the 4th element. I'm not sure if this is a regression or maybe something else that could be a new feature added to peakrdl python. If it is the latter I can open up another ticket.

**Comment by krcb197** [comment]
@apstrike

The SystemRDL specification does not have a clear and explicit explanation of the case of registers within an memory. However if you consider the case of multiple registers, exceeding the width of an single memory entry, I believe the behaviour is correct.

However, if there is something I have missed, please let me know.


Keith

**Comment by apstrike** [comment]
@krcb197 

no, that's not the case I'm talking about. Sorry maybe I wasn't too clear.

From chapter 11 of the systemRDL 2.0 spec:
```
Child instances within a memory 
are virtual instances. A virtual instance does not have a physical implementation, but, it is a software view of 
the memory data. A memory can contain instances of virtual registers and fields within a virtual register are 
virtual fields.
```

I think the purpose of the virtual registers within a memory are to be able to structure what the memory element is supposed to look like. so for example, if I have:

```
external mem {
   mementries = 256;
   memwidth=128;
   
   reg {
       regwidth=128;
       field {} my_field[128];
    } my_reg;
} my_mem;
```

then I think this is supposed to be describing a memory 128b wide with 256 elements in it and each element is structured as a 128b register with a 128 bit field.

I thought the `Mem` object was indexable and with it you could attempt to read a virtual register within a memory element and that there was a regression in that feature. But I think I've realized that this was never a thing in PeakRDL-python to begin with.

**Comment by krcb197** [comment]
I think the key is the word: _memory_ in the clause highlighted as opposed to: _memory entry_

> Child instances within a memory are virtual instances. A virtual instance does not have a physical implementation, but, it is a software view of the memory data. A memory can contain instances of virtual registers and fields within a virtual register are 
virtual fields.

The registers would be packed into the memory, I have used these in a number of designs. Consider the following example with 5 control registers stored in an NVM (for example a flash) that can be copied to the internal registers after power on. To make this example more interesting I have made it with 128-bit lines.

``` systemrdl
addrmap calibration_nvm_example {

    reg control_reg_a_def {
        field { } setting[31:0];
    };

    reg control_reg_b_def {
        field { } setting[31:0];
    };

    reg control_reg_c_def {
        field { } setting[31:0];
    };

    reg control_reg_d_def {
        field { } setting[31:0];
    };

    reg control_reg_e_def {
        field { } setting[31:0];
    };

    external mem {
        mementries = 16;
        memwidth = 128;
        sw=rw;

        control_reg_a_def control_reg_a;
        control_reg_b_def control_reg_b;
        control_reg_b_def control_reg_c;
        control_reg_b_def control_reg_d;
        control_reg_b_def control_reg_e;

    } nvm;

    regfile {
        control_reg_a_def control_reg_a;
        control_reg_b_def control_reg_b;
        control_reg_b_def control_reg_c;
        control_reg_b_def control_reg_d;
        control_reg_b_def control_reg_e;
    } control_registers;
};
```

If this is processed with peakrdl HTML you see the registers are packed into the memory on 32-bit boundaries, with one copy of the registers, rather than one register per memory entry.
![image](https://github.com/user-attachments/assets/13c9a056-b6b6-4070-8108-003e734d2d02)

Therefore I think the behaviour of the python wrapper, where the registers are presented at the top level (rather than inside the indices) is correct.

**Comment by apstrike** [comment]
ah, I see what you mean. Yes I think I may have misunderstood that paragraph then. Ok thank you very much for the insight!

**Comment by krcb197** [comment]
I have made a minor improvement to help users making the migration. In the meantime this will stay on a release candidate as I intend to include some other features in 0.9.0.
