### ISSUE TITLE
RDLFormatCode support

### ISSUE THREAD

**Issue by krcb197** [krcb197/PeakRDL-python#24]
[SystemRDL 2.0 ](https://www.accellera.org/images/downloads/standards/systemrdl/SystemRDL_2.0_Jan2018.pdf) specifies a set formating tags, see appendix H: 

> The RDLFormatCode tags shall be interpreted by the SystemRDL compiler and rendered in the generated output

These only apply to the `name` and `desc` properties.

For example the following
```
addrmap RDLFormatCode_example {

    reg {
        field { name = "field a"; desc="A field with a [b]bold[/b], [i]Italic[/i], [u]underline[/u] and [code]code[/code]"; } field_a[31:0];
    } reg_a;

};
```

current this produces the following output:
```python
class RDLFormatCode_example_reg_a_field_a_cls(FieldReadWrite):
    
    """
    Class to represent a register field in the register model

    +-------------------+------------------------------------------------+
    | System RDL Field  | Value                                          |
    +===================+================================================+
    | Name              | field a                                        |
    +-------------------+------------------------------------------------+
    | Description       | A field with a [b]bold[/b], [i]Italic[/i],     |
    |                   | [u]underline[/u] and [code]code[/code]         |
    +-------------------+------------------------------------------------+
    """

    __slots__ = []
```

This table format looks quite nice for plain text descriptions but clearly does not work for the formatted fields. The thought was to ensure it rendered nicely in plain text documentation (as source code) or if the code is run through Sphinx to create software documentation of the wrappers as part of a larger software module.

The system RDL compiler provides a helpful [`get_html_desc`](https://systemrdl-compiler.readthedocs.io/en/latest/api/node.html#systemrdl.node.Node.get_html_desc) method on each node to convert RDLFormatCode to HTML. There are some additional considerations for example if headers are used these need to be incremented, this is handled in the PeakRDL-html project.

**Comment by krcb197** [comment]
I have opted to use the raw pass through reStructuredText directive. The plain text header file is not brilliant. However, the resultant Sphinx documentation created with autodoc is pretty good.

**Comment by ozel** [comment]
Having the `name` and `desc` properties accessible from python would be quite nice for user interaction and  logging purposes.
Maybe they could be simply added to the .udp dictionary on demand when explicitly requested via the --udp option?
Thanks for this awesome project, the included simulator is very useful!

**Comment by krcb197** [comment]
@ozel 

Thank you for positive feedback, I am never sure how many people are using this.

I think this would be a neat feature. Rather than have this within the comment thread of an existing closed issue, can you make a new issue for the request.

Rather than put this in the UDP structure, I would favour making the name and desc properties of the class, this would return an object that allowed the user to access either:
- the raw version (as it appears in the systemRDL) 
- converted from RDlFormatCode to HTML

Do you fancy having a go at making this enhancement yourself (with some guidance if wanted)?

**Comment by ozel** [comment]
Thanks, I had a brief look into the exporter code. if I understand it well, the properties are already accessible (of course) in node dictionaries, that means one would mainly need to extend the Jinja templates?
I've not worked with those templates before but would be open to try it. I'll make a dedicated issue as suggested as soon as I get to tinker a bit more with your code base!

**Comment by krcb197** [comment]
I have made an new issue for this, see #167
