### ISSUE TITLE
Provide more field attributes

### ISSUE THREAD

**Issue by mpriestleyidex** [krcb197/PeakRDL-python#46]
Such as;
- default (reset) value
- sw and hw read/write mode

I'm mainly thinking about automated register testing here, but the 'volatility' of registers has wider uses.

**Comment by krcb197** [comment]
This is a good idea, I have started staking a look at it

**Comment by krcb197** [comment]
I have cherrypicked this change out of your repository into a branch on the peakrdl-python repo. I will go in an add a test for this

**Comment by mpriestleyidex** [comment]
OK. I was still mulling on a better name for "misc props", but it'll do.

**Comment by krcb197** [comment]
I think this is a good name, they are properties that don't directly influence the generation of the code but are never-the-less pass through. Also this class is not exposed to most users who only see the property on the filed itself
