### ISSUE TITLE
Provide parent property for all nodes and fields

### ISSUE THREAD

**Issue by mpriestleyidex** [krcb197/PeakRDL-python#49]
As mentioned in #47, if all nodes and fields provide a `parent` property then it's possible to navigate back up the tree from anywhere.

I propose adding this property to the `Base` class.
I'll make a PR for this.

**Comment by krcb197** [comment]
@mpriestleyidex, I have had a look at the changes you have made on the branch in your repo. These look fairly sensible to me, I suggest the go together with the changes on iterating through the address map. Can you create a pull request to put them on the  #56 branch
