### ISSUE TITLE
Support registers within memories

### ISSUE THREAD

**Issue by mpriestleyidex** [krcb197/PeakRDL-python#51]
The following RDL uses registers / fields to describe the internal structure of a memory:

```
addrmap memories {
    external mem {
        mementries = 2;
        memwidth = 32;
        sw = rw;

        reg entry {
            field {} lower[15:0];
            field {} upper[31:16];
        };

        entry stuff[2] @ 0 += 4;
    } mem_with_regs_and_fields;
};
```

The generated model does not provide these as attributes of the memory class.
However, the generated test suite attempts to access the regs / fields as attributes of the memory class, and fails.

**Comment by krcb197** [comment]
I have added a new test for this and I can see you are correct, this is a bug. One of my own projects has register definitions within memory so I am surprised I hadn't found that one too,
