### ISSUE TITLE
Include array subscript in inst_name

### ISSUE THREAD

**Issue by mpriestleyidex** [krcb197/PeakRDL-python#53]
Let's say I have an addrmap `FOO` containing an array of registers `BAR`. At present `FOO.BAR[3].inst_name` returns "BAR". I think it's more helpful to return "BAR[3]". Certainly the option should be available.

Perhaps something like:
```
def get_inst_name(self, subscript:bool=True) -> str:
    name = self.__inst_name
    if subscript and self.array_index is not None:
        name = name + "[" + self.array_index + "]
    return name

inst_name = property(fget=get_inst_name)
```

**Comment by krcb197** [comment]
@mpriestleyidex 

I am inclined to agree with you, I think would go further and always return the name with the array subscript. i.e. update the inst_name parameter for an array to provide the subscript form

**Comment by krcb197** [comment]
I have thought about this a bit more. As it is the instance name by definition it has to be the version with the subscript. I am more convinced that updating the `inst_name` is the solution
