### ISSUE TITLE
Provide get-by-name

### ISSUE THREAD

**Issue by mpriestleyidex** [krcb197/PeakRDL-python#61]
Imagine if you will a set of register / field values stored in say a JSON file, which you'd like to write to the target:

```
"SOME_SECTION" : {
  "REG_A" : {
    "F_A" : 0x12,
    "F_B" : 0x34
  },
  "REG_B" : 0x5678,
  "REG_ARR" = [ 12, 14, 16, 28 ],
  "REG_ARR[7]" = 29
}
```

Currently everything is just a member of the thing above, so getting from a string name to the actual object is nasty (yes, I'm sure there's some magic that could be done with `eval`, or indexing `__attrs__`, but I don't think it's going to be pretty).

It's be nice if the user could do something like:
```
reg_model.get_by_name("SOME_SECTION").get_by_name("REG_B").write(0x5678)
```
and once those arguments are variables one can imagine replaying the example JSON into the register map with minimal fuss.

**Comment by krcb197** [comment]
I don't think this example need new methods on the classes, the existing python `getattr`, `hasattr` and `setattr` allow it to be done. I have added a new example to the Pull Request we have on the go.

**Comment by mpriestleyidex** [comment]
OK, that's less fiddly than I'd expected. But it's worth considering that:
- get by name wouldn't suffer from name clashes as in #60 
- if you mangle the attribute names as suggested in #60, the attribute name and the node name would differ.

**Comment by krcb197** [comment]
I agree we will need a translation between the original node names from the systemRDL and the name used within the Python Wrapper. I would like to close this ticket, mainly as I associated with the #56 and deal with the name mangling as part of #60 (which has a seperate branch). Is that OK?
