### ISSUE TITLE
Add option to not generate tests

### ISSUE THREAD

**Issue by mpriestleyidex** [krcb197/PeakRDL-python#79]
I'm using this on the RDL of a fairly modest ASIC, and peakrdl-python takes nearly 3 minutes to export (vs a few seconds for all other exporters).

Some select highlights from a run through cProfile:
```
         218995202 function calls (214683105 primitive calls) in 168.494 seconds

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  168.522  168.522 __main__.py:1(<module>)
        1    0.000    0.000  165.605  165.605 __peakrdl__.py:36(do_export)
     4577    0.009    0.000    5.691    0.001 addrmap.py.jinja:5(root)
        5    0.000    0.000    0.035    0.007 addrmap_memory.py.jinja:5(root)
      227    0.039    0.000    1.483    0.007 addrmap_register.py.jinja:18(macro)
  2693011    3.773    0.000  151.333    0.000 addrmap_tb.py.jinja:5(root)

 24183147    4.779    0.000    4.779    0.000 safe_name_utility.py:132(<lambda>)
   389903    4.988    0.000   13.681    0.000 safe_name_utility.py:139(is_safe_memory_name)
 16765829    3.293    0.000    3.293    0.000 safe_name_utility.py:168(<lambda>)
   468613    5.784    0.000   15.518    0.000 safe_name_utility.py:211(is_safe_addrmap_name)
 20150359    3.892    0.000    3.892    0.000 safe_name_utility.py:232(<lambda>)
  1700549    5.688    0.000  101.818    0.000 safe_name_utility.py:252(safe_node_name)
   454937    1.205    0.000  107.836    0.000 safe_name_utility.py:295(get_python_path_segments)
  1700549    1.906    0.000    2.198    0.000 safe_name_utility.py:30(_python_name_checks)
2135305/454937    3.467    0.000  104.672    0.000 safe_name_utility.py:311(node_segment)
   386757    6.639    0.000   30.305    0.000 safe_name_utility.py:51(is_safe_field_name)
 20100243    4.026    0.000    4.026    0.000 safe_name_utility.py:87(<lambda>)
   454952    7.802    0.000   26.849    0.000 safe_name_utility.py:94(is_safe_register_name)

  1703411   30.371    0.000   30.371    0.000 {built-in method builtins.dir}
```

From which I infer that most of the time is spent generating the testbench, and a big chunk of that is spent checking for name safety. I'm not sure what the 30s of `builtins.dir` might be saying.

In general I'm not interested in creating / running the generated tests (perhaps I'll add this to a weekly regression), and would quite happily turn that off to turn 170s into 17.

It's likely that there are performance optimisations that could be made (recursion is expensive in python), but turning off stuff I don't need (or don't need every time) seems like a sensible thing to do anyway.

**Comment by krcb197** [comment]
@mpriestleyidex that data is quite insightful I think that that gives me some hints how to optimise this.

The `dir` is used to looking for name clashes with the library classes, that can be improved by doing the operation once when the module is imported. Let me look at optimising that. 

I can add a skip option for the unit tests but I am reluctant to encourage generating the python wrappers without running the tests as some issues only come to light once the tests are run. I would prefer to try optimising the generation process in the first instance.

**Comment by krcb197** [comment]
@mpriestleyidex 

The option to skip the generation of the test code has gone into the latest 0.3.10 release.

There is also an optimisation to the way the safe names are managed to only extract the list of potential name clashes with the base class once, rather than doing it every time the function is call. That resulted in a 30% reduction in time on the most complex of the test cases. I would be interested to see how much of an improvement it has on your design.

**Comment by mpriestleyidex** [comment]
With 3.10:

```
        1    0.000    0.000   91.532   91.532 __main__.py:1(<module>)
        1    0.000    0.000   88.772   88.772 __peakrdl__.py:38(do_export)
     4577    0.008    0.000    5.192    0.001 addrmap.py.jinja:5(root)
  2693011    3.367    0.000   75.707    0.000 addrmap_tb.py.jinja:5(root)

        1    0.000    0.000    0.006    0.006 safe_name_utility.py:1(<module>)
   454952    1.525    0.000    4.791    0.000 safe_name_utility.py:106(is_safe_register_name)
   389903    0.714    0.000    1.457    0.000 safe_name_utility.py:149(is_safe_memory_name)
      324    0.001    0.000    0.001    0.000 safe_name_utility.py:183(is_safe_regfile_name)
   468613    0.694    0.000    1.531    0.000 safe_name_utility.py:217(is_safe_addrmap_name)
        1    0.000    0.000    0.000    0.000 safe_name_utility.py:242(_NodeProcessingScheme)
  1700549    4.502    0.000   30.374    0.000 safe_name_utility.py:254(safe_node_name)
        8    0.000    0.000    0.000    0.000 safe_name_utility.py:29(_build_class_method_list)
   454937    1.057    0.000   36.352    0.000 safe_name_utility.py:297(get_python_path_segments)
      396    0.000    0.000    0.000    0.000 safe_name_utility.py:30(<lambda>)
2135305/454937    2.916    0.000   33.561    0.000 safe_name_utility.py:313(node_segment)
  1700549    1.732    0.000    2.013    0.000 safe_name_utility.py:44(_python_name_checks)
   386757    1.296    0.000   10.065    0.000 safe_name_utility.py:65(is_safe_field_name)

     2870    0.072    0.000    0.072    0.000 {built-in method builtins.dir}
```

And with the `--skip_test_case_generation` option it's down to 8s in total. Which drops to 4 when I turn the profiler off. (Always good to remember that the profiler adds overhead and probably distorts the relative time of code segments).

Anyway, a great improvement. Thanks.

**Comment by krcb197** [comment]
That is good news, I plan to do some more optimisation on this. However, my next approach to using LRUcache in functools needs the systemrdl-compiler objects to be hashable.
